name: Update measures

on:
  schedule:
    - cron: "0 7 * * *" 
  workflow_dispatch:

jobs:
  run-function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run MeasureRealtimePipeline
        run: |
          python -c "from src.pipeline.measures import MeasureRealtimePipeline; MeasureRealtimePipeline()"
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
